CREATE TABLE IF NOT EXISTS app_user (
  id SERIAL PRIMARY KEY,
  org_id INTEGER NOT NULL REFERENCES organization(id),
  email VARCHAR(320) NOT NULL UNIQUE,
  hashed_password VARCHAR(255) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
